# Generated by Django 4.1.6 on 2023-02-19 14:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('Title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('demo_link', models.CharField(max_length=1000)),
                ('source_link', models.CharField(max_length=1000)),
                ('vote_total', models.IntegerField(default=0, editable=False)),
                ('vote_ratio', models.IntegerField(default=0, editable=False)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
