# Generated by Django 4.1.6 on 2023-02-20 14:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_project_demo_link_alter_project_source_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rewiev',
            fields=[
                ('body', models.TextField(blank=True, null=True)),
                ('value', models.CharField(choices=[('UP', 'UP'), ('DOWN', 'DOWN')], max_length=50)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.project')),
            ],
        ),
    ]
